### ISSUE TITLE
待付款也会提醒金额，是bug么

### ISSUE THREAD

**Issue by Gxz-NGU** [lyqiangmny/zhihu-money-come#1]
京粉待付款的卡片也会进行提醒~
感觉待付款也进行提醒， 总会有种失落感。

**Comment by Gxz-NGU** [comment]
对响应新增了一个validCode的判断，不是已付款的通通过滤。
就不提pr了，有需要的同学可以在这个[ZhiHuJdMoneyCome.java](https://github.com/lyqiangmny/zhihu-money-come/blob/main/src/main/java/com/lyqiang/money/come/quartz/ZhiHuJdMoneyCome.java)文件的第62行加多中间那句if判断

```
JSONObject data = dataArr.getJSONObject(i);
if (data.getBigDecimal("validCode").compareTo(new BigDecimal(16)) != 0 ) {break;} // 有效码不是已付款状态就都跳过
BigDecimal estimateFee = data.getBigDecimal("estimateFee");
```

**Comment by lyqiangmny** [comment]
> 京粉待付款的卡片也会进行提醒~
> 感觉待付款也进行提醒， 总会有种失落感。

不是bug,获取的是所有状态的订单，没有进行单独过滤，预期是只要有单子就提醒。

**Comment by lyqiangmny** [comment]
> 京粉待付款的卡片也会进行提醒~
> 感觉待付款也进行提醒， 总会有种失落感。

后续加个开关，可以自由控制是否提醒代付款的单子，感谢反馈。

**Comment by Gxz-NGU** [comment]
待付款的提示挺好的，就是标注一下这单不是已付款。
我现在是直接把除了已付款的单子都标注为0元，这样一看0元心里大概就有个数了
